name: Visual regression testing

on:
  pull_request:
    branches: [main]

jobs:
  build_storybook:
    if: ${{ github.event.label.name == 'visual-test:required' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build storybook & run visual tests
        run: yarn nx run nucleus:visual-test
